CREATE DATABASE MySQLFakeAPI;
USE MySQLFakeAPI;
CREATE TABLE PRODUTOS (
    ID INT NOT NULL AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRODUCT_DESCRIPTION TEXT NOT NULL,
    PRIMARY KEY (ID)
);
